print("enter the name of cat 1:")
catname1 = input()
print("enter the name of cat 2:")
catname2 = input()
print("enter the name of cat 3:")
catname3 = input()
print("enter the name of cat 3:")
catname3 = input()
print("enter the name of cat 4:")
catname4 = input()
print("enter the name of cat 5:")
catname5 = input()
print("enter the name of cat 6:")
catname6 = input()

print("the cat names are:")
print(catname1 + " " + catname2 + " " + catname3, end = " ")
print(catname4 + " " + catname5 + " " + catname6)